spring.application.name=energy-api
# PostgreSQL Datenbankverbindung
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=disysuser
spring.datasource.password=disyspw

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
